# Generated by Django 3.2.7 on 2021-10-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smishing.member'),
        ),
    ]
