# Generated by Django 3.2.7 on 2021-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smishing', '0002_alter_guide_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(db_column='UserID', default='', primary_key=True, serialize=False),
        ),
    ]
