# Generated by Django 3.2.7 on 2021-10-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smishing', '0005_alter_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
