# Generated by Django 3.2.7 on 2021-10-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smishing', '0006_auto_20211015_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20, verbose_name='Sender')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='SendDate')),
                ('contents', models.CharField(max_length=150, verbose_name='Contents')),
                ('smishing_sort', models.BooleanField(default=False, verbose_name='SmishingSort')),
                ('member_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smishing.member')),
            ],
        ),
    ]
