# Generated by Django 3.2.7 on 2021-10-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smishing_nlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='smishing_message',
        ),
    ]
