# Generated by Django 3.2.7 on 2021-10-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smishing_nlp', '0002_alter_message_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
